import { App, ItemView, Modal, Notice, Plugin, PluginSettingTab, Setting, TFile, TFolder, WorkspaceLeaf, normalizePath } from "obsidian";
import { registerDashboardModule, registerDashboardWidget } from "./dashboard-bridge";

type Rating = "thriving" | "healthy" | "attention" | "struggling" | "crisis";
type Cadence = "weekly" | "biweekly" | "monthly";
type CheckupKind = "family" | "marriage" | "kids";
type TargetKind = "family" | "marriage" | "member";
type Area = { id: string; name: string; prompt: string; scriptures: string[]; order?: number; defaultRating?: Rating; enabledTargets?: TargetKind[]; enabledCheckups?: CheckupKind[]; promptByCheckup?: Partial<Record<CheckupKind, string>> };
type Target = { id: string; label: string; kind: TargetKind; path?: string; role?: string };
type CheckIn = { id: string; date: string; cadence: Cadence; kind: CheckupKind; targets: string[]; ratings: Record<string, Record<string, Rating>>; answers: Record<string, Record<string, string>>; focuses: Record<string, Record<string, string>>; nextSteps: Record<string, Record<string, string>>; path: string; legacy?: boolean };
type Member = { id: string; name: string; role: string; status: string; needs: string[]; focuses: string[]; path: string };
type Settings = { rootFolder: string; cadence: Cadence; areas: Area[]; migrationVersion?: number; defaultCheckupKind?: CheckupKind; requireSpouses?: boolean; trendHistory?: number };

const VIEW = "marriage-companion-dashboard";
const MEMBER_START = "<!-- marriage-companion:member:start -->";
const MEMBER_END = "<!-- marriage-companion:member:end -->";
const RATING_ORDER: Rating[] = ["thriving", "healthy", "attention", "struggling", "crisis"];
const RATING_LABELS: Record<Rating, string> = { thriving: "Thriving", healthy: "Healthy", attention: "Needs attention", struggling: "Struggling", crisis: "Crisis" };
const RATING_SYMBOLS: Record<Rating, string> = { thriving: "✦", healthy: "●", attention: "▲", struggling: "◆", crisis: "!" };
const CHECKUP_LABELS: Record<CheckupKind, string> = { family: "Family checkup", marriage: "Marriage checkup", kids: "Kids checkup" };

const DEFAULT_AREAS: Area[] = ([
  ["communication", "Communication", "Where did we listen well, and where do we need to speak truth in love?", ["James 1:19", "Ephesians 4:29"], ["family", "marriage"], ["family", "marriage"]],
  ["marriage", "Marriage relationship", "How are we pursuing one another with covenant love and patience?", ["Ephesians 5:25", "Colossians 3:14"], ["marriage"], ["marriage"]],
  ["intimacy", "Intimacy", "Where can we pursue tenderness, honor, and self-giving love?", ["1 Corinthians 7:3–5"], ["marriage"], ["marriage"]],
  ["direction", "Direction and goals", "What faithful next step is God putting before us?", ["Proverbs 16:9"], ["family", "marriage"], ["family", "marriage"]],
  ["children", "Children and parenting", "How can we shepherd each child with wisdom, patience, and joy?", ["Deuteronomy 6:6–7"], ["family", "marriage"], ["family"]],
  ["finances", "Finances", "Are our resources being handled faithfully and peacefully?", ["Matthew 6:21"], ["family", "marriage"], ["family", "marriage"]],
  ["friends", "Friends", "Are our friendships helping us love God and neighbor well?", ["Proverbs 13:20"], ["family", "marriage"], ["family", "marriage"]],
  ["extended-family", "Extended family", "Where do we need honor, boundaries, forgiveness, or care?", ["Romans 12:18"], ["family", "marriage"], ["family", "marriage"]],
  ["leisure", "Leisure", "Is our rest and entertainment refreshing rather than ruling us?", ["1 Corinthians 10:31"], ["family", "marriage"], ["family", "marriage"]],
  ["church", "Church", "How are we worshiping, serving, and belonging in Christ's body?", ["Hebrews 10:24–25"], ["family", "marriage"], ["family", "marriage"]],
  ["christ", "Relationship with Christ", "How are we abiding in Christ individually and together?", ["John 15:4–5"], ["family", "marriage", "member"], ["family", "marriage", "kids"]],
  ["headspace", "Headspace", "What burdens, fears, or patterns need patient attention and prayer?", ["Philippians 4:6–7"], ["family", "marriage", "member"], ["family", "marriage", "kids"]],
  ["household", "Household", "What practical rhythms would bring peace and faithful stewardship?", ["1 Corinthians 14:40"], ["family", "marriage"], ["family", "marriage", "kids"]],
  ["health", "Health and rest", "How are we caring for the bodies and limits God has given us?", ["1 Corinthians 6:19–20"], ["family", "marriage", "member"], ["family", "marriage", "kids"]],
  ["emotional-wellbeing", "Emotional wellbeing", "What emotions and needs should be named with patience and care?", ["Galatians 6:2"], ["member"], ["kids"]],
  ["friendships", "Friendships", "How are friendships shaping this child’s character and faith?", ["1 Corinthians 15:33"], ["member"], ["kids"]],
  ["character", "Character and responsibility", "Where can we practice truth, diligence, kindness, and self-control?", ["Galatians 5:22–23"], ["member"], ["kids"]],
  ["school", "School", "What support or encouragement is needed in learning and responsibilities?", ["Proverbs 1:5"], ["member"], ["kids"]],
  ["parent-child", "Parent-child relationship", "How can we grow trust, affection, correction, and delight?", ["Ephesians 6:4"], ["member"], ["kids"]]
] as [string, string, string, string[], TargetKind[], CheckupKind[]][]).map(([id, name, prompt, scriptures, enabledTargets, enabledCheckups], index) => ({ id, name, prompt, scriptures, enabledTargets, enabledCheckups, order: index + 1, defaultRating: "healthy" as Rating }));
const DEFAULT: Settings = { rootFolder: "Marriage Companion", cadence: "weekly", areas: DEFAULT_AREAS, defaultCheckupKind: "family", requireSpouses: true, trendHistory: 8 };
const today = (): string => new Date().toISOString().slice(0, 10);
const makeId = (prefix: string): string => `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;
const safe = (value: string): string => value.trim().replace(/[\\/:*?"<>|#^[\]]+/g, " ").replace(/\s+/g, " ").replace(/[. ]+$/g, "") || "Note";
const list = (value: unknown): string[] => Array.isArray(value) ? value.map(String) : typeof value === "string" && value.trim() ? [value.trim()] : [];
const ratingOf = (value: unknown): Rating => RATING_ORDER.includes(value as Rating) ? value as Rating : "attention";
const shortDate = (value: string): string => value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";
const kindOf = (value: unknown): CheckupKind => value === "marriage" || value === "kids" ? value : "family";

class FamilyRepository {
  constructor(private app: App, private settings: Settings) {}
  update(settings: Settings): void { this.settings = settings; }
  get root(): string { return normalizePath(this.settings.rootFolder.trim().replace(/^\/+|\/+$/g, "") || DEFAULT.rootFolder); }
  async initialize(): Promise<void> { for (const folder of [this.root, `${this.root}/Check-ins`, `${this.root}/Members`, `${this.root}/Children`, `${this.root}/Migration Backups`]) await this.ensureFolder(folder); }
  private async ensureFolder(path: string): Promise<void> { const normalized = normalizePath(path); const existing = this.app.vault.getAbstractFileByPath(normalized); if (existing instanceof TFolder) return; if (existing instanceof TFile) throw new Error(`Cannot create folder because a file already exists at ${normalized}.`); try { await this.app.vault.createFolder(normalized); } catch (error) { const retry = this.app.vault.getAbstractFileByPath(normalized); if (!(retry instanceof TFolder) && !/already exists/i.test(String(error))) throw error; } }
  private fm(file: TFile): Record<string, any> { return (this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}) as Record<string, any>; }
  private files(): TFile[] { return this.app.vault.getMarkdownFiles().filter(file => file.path.startsWith(`${this.root}/`)); }
  members(): Member[] { const found = new Map<string, Member>(); for (const file of this.files().filter(item => ["marriage-companion-member", "marriage-companion-child"].includes(this.fm(item).type))) { const fm = this.fm(file); const member = { id: String(fm.member_id ?? fm.child_id ?? file.basename), name: String(fm.name ?? file.basename), role: String(fm.role ?? "child"), status: String(fm.status ?? "active"), needs: list(fm.needs), focuses: list(fm.focuses), path: file.path }; const existing = found.get(member.id); if (!existing || file.path.includes("/Members/")) found.set(member.id, member); } return [...found.values()].sort((a, b) => a.name.localeCompare(b.name)); }
  targets(): Target[] { return [{ id: "family", label: "Whole family", kind: "family" }, { id: "marriage", label: "Marriage", kind: "marriage" }, ...this.members().filter(member => member.status !== "inactive").map(member => ({ id: member.id, label: member.name, kind: "member" as const, path: member.path, role: member.role }))]; }
  spouses(): Member[] { return this.members().filter(member => member.status === "active" && member.role.toLowerCase() === "spouse"); }
  children(): Member[] { return this.members().filter(member => member.status === "active" && member.role.toLowerCase() === "child"); }
  areasFor(kind: CheckupKind, target: Target): Area[] { return this.settings.areas.filter(area => { const checks = area.enabledCheckups; const targets = area.enabledTargets; return (!checks?.length || checks.includes(kind)) && (!targets?.length || targets.includes(target.kind)); }).sort((a, b) => (a.order ?? 0) - (b.order ?? 0)); }
  checkins(): CheckIn[] { return this.files().filter(file => ["marriage-companion-checkin", "family-companion-checkin"].includes(this.fm(file).type)).map(file => { const fm = this.fm(file); const oldRatings = fm.ratings && typeof fm.ratings === "object" ? fm.ratings : {}; const values = Object.values(oldRatings); const nested = values.length === 0 || values.every(value => value && typeof value === "object" && !Array.isArray(value)); const targets = list(fm.targets).length ? list(fm.targets) : ["family"]; const legacy = fm.type === "marriage-companion-checkin" || fm.legacy_scope === "shared-marriage-checkin" || fm.legacy_scope === "shared-checkup"; return { id: String(fm.checkin_id ?? fm.id ?? ""), date: String(fm.date ?? ""), cadence: (fm.cadence === "monthly" || fm.cadence === "biweekly" ? fm.cadence : "weekly") as Cadence, kind: kindOf(fm.checkup_kind), targets, ratings: (nested ? oldRatings : { family: oldRatings }) as Record<string, Record<string, Rating>>, answers: (fm.answers && typeof fm.answers === "object" ? fm.answers : {}) as Record<string, Record<string, string>>, focuses: (fm.focuses && typeof fm.focuses === "object" ? fm.focuses : {}) as Record<string, Record<string, string>>, nextSteps: (fm.next_steps && typeof fm.next_steps === "object" ? fm.next_steps : {}) as Record<string, Record<string, string>>, path: file.path, legacy }; }).sort((a, b) => b.date.localeCompare(a.date)); }
  latestFor(target: string): CheckIn | undefined { return this.checkins().find(checkin => checkin.targets.includes(target) || checkin.ratings[target]); }
  due(): boolean { const latest = this.checkins()[0]; const days = this.settings.cadence === "monthly" ? 30 : this.settings.cadence === "biweekly" ? 14 : 7; return !latest || latest.date < new Date(Date.now() - days * 86400000).toISOString().slice(0, 10); }
  async createMember(name: string, role: string, needs: string[], focuses: string[]): Promise<TFile> { await this.initialize(); const memberId = makeId("MBR"); const path = normalizePath(`${this.root}/Members/${safe(name)}.md`); if (this.app.vault.getAbstractFileByPath(path)) throw new Error("A member with that name already exists."); return this.app.vault.create(path, `---\ntype: marriage-companion-member\nmember_id: ${memberId}\nname: ${JSON.stringify(name)}\nrole: ${role}\nstatus: active\nneeds:\n${needs.length ? needs.map(value => `  - ${JSON.stringify(value)}`).join("\n") : "  []"}\nfocuses:\n${focuses.length ? focuses.map(value => `  - ${JSON.stringify(value)}`).join("\n") : "  []"}\ncreated: ${today()}\nupdated: ${today()}\n---\n\n# ${name}\n\n${MEMBER_START}\nMember summary will be generated by Family Companion.\n${MEMBER_END}\n\n## Personal notes\n\n`); }
  async createCheckin(input: { kind: CheckupKind; date: string; targets: string[]; ratings: Record<string, Record<string, Rating>>; answers: Record<string, Record<string, string>>; focuses: Record<string, Record<string, string>>; nextSteps: Record<string, Record<string, string>> }): Promise<TFile> { await this.initialize(); const date = input.date || today(); let path = normalizePath(`${this.root}/Check-ins/${date} ${CHECKUP_LABELS[input.kind].replace(" checkup", "")}.md`); let suffix = 2; while (this.app.vault.getAbstractFileByPath(path)) path = normalizePath(`${this.root}/Check-ins/${date} ${CHECKUP_LABELS[input.kind].replace(" checkup", "")} ${suffix++}.md`); const targetMap = new Map(this.targets().map(target => [target.id, target])); const body = input.targets.map(targetId => { const target = targetMap.get(targetId); const rows = this.settings.areas.filter(area => input.ratings[targetId]?.[area.id]).map(area => `### ${area.name}\n\n- Rating: ${input.ratings[targetId][area.id]}\n- Answer: ${input.answers[targetId]?.[area.id] || "—"}\n- Focus: ${input.focuses[targetId]?.[area.id] || "—"}\n- Next step: ${input.nextSteps[targetId]?.[area.id] || "—"}\n- Scripture: ${area.scriptures.join("; ")}\n\n${area.promptByCheckup?.[input.kind] ?? area.prompt}\n`).join("\n"); return `## ${target?.label ?? targetId}\n\n${rows}`; }).join("\n"); const yaml = [`---`, `type: family-companion-checkin`, `schema_version: 3`, `checkup_kind: ${input.kind}`, `checkin_id: ${makeId("CHK")}`, `date: ${date}`, `cadence: ${this.settings.cadence}`, `targets:`, ...input.targets.map(target => `  - ${target}`), `ratings:`, ...this.yamlNested(input.ratings), `answers:`, ...this.yamlNested(input.answers), `focuses:`, ...this.yamlNested(input.focuses), `next_steps:`, ...this.yamlNested(input.nextSteps), `created: ${new Date().toISOString().slice(0, 16)}`, `updated: ${new Date().toISOString().slice(0, 16)}`, `---`].join("\n"); return this.app.vault.create(path, `${yaml}\n\n# ${CHECKUP_LABELS[input.kind]} — ${date}\n\nAsk the Lord for humility, honesty, gentleness, and hope in Christ.\n\n${body}\n`); }
  private yamlNested(values: Record<string, Record<string, string>>): string { const lines: string[] = []; for (const [target, areas] of Object.entries(values)) { lines.push(`  ${target}:`); for (const [area, value] of Object.entries(areas)) lines.push(`    ${area}: ${JSON.stringify(value)}`); } return lines.length ? lines.join("\n") : "  {}"; }
  async migrateV3(): Promise<{ changed: number; backup: string; journal: string }> { await this.initialize(); const files = this.files().filter(file => ["marriage-companion-checkin", "family-companion-checkin"].includes(this.fm(file).type)); const stamp = new Date().toISOString().replace(/[:.]/g, "-"); const backupRoot = normalizePath(`${this.root}/Migration Backups/${stamp}-v3`); await this.ensureFolder(backupRoot); const entries: string[] = []; let changed = 0; for (const file of files) { const original = await this.app.vault.read(file); const backupPath = normalizePath(`${backupRoot}/${file.path.slice(this.root.length + 1).replace(/[\\/]/g, " - ")}`); if (!this.app.vault.getAbstractFileByPath(backupPath)) { const backup = await this.app.vault.create(backupPath, original); if (await this.app.vault.read(backup) !== original) throw new Error(`Backup verification failed for ${file.path}`); } const fm = this.fm(file); if (fm.schema_version === 3 && fm.checkup_kind) { entries.push(`- Unchanged: ${file.path}`); continue; } await this.app.fileManager.processFrontMatter(file, frontmatter => { const oldRatings = frontmatter.ratings && typeof frontmatter.ratings === "object" ? frontmatter.ratings : {}; const values = Object.values(oldRatings); const nested = values.length === 0 || values.every(value => value && typeof value === "object" && !Array.isArray(value)); frontmatter.type = "family-companion-checkin"; frontmatter.schema_version = 3; frontmatter.checkup_kind = "family"; frontmatter.legacy_scope = "shared-checkup"; frontmatter.targets = ["family"]; frontmatter.ratings = nested ? oldRatings : { family: oldRatings }; frontmatter.answers = frontmatter.answers ?? {}; frontmatter.focuses = frontmatter.focuses ?? {}; frontmatter.next_steps = frontmatter.next_steps ?? {}; frontmatter.updated = frontmatter.updated ?? today(); }); changed++; entries.push(`- Migrated: ${file.path}`); } const journal = normalizePath(`${backupRoot}/Migration Journal.md`); await this.app.vault.create(journal, `---\ntype: family-companion-migration\nschema_version: 3\ncreated: ${new Date().toISOString()}\nchanged: ${changed}\n---\n\n# Family Companion v3 migration\n\n${entries.join("\n") || "- No records found."}\n`); return { changed, backup: backupRoot, journal }; }
  verifyMigration(): { legacy: number; v3: number; members: number; backups: number } { const checks = this.checkins(); return { legacy: checks.filter(check => check.legacy).length, v3: checks.filter(check => check.kind).length, members: this.members().length, backups: this.app.vault.getAllLoadedFiles().filter(file => file.path.startsWith(`${this.root}/Migration Backups/`) && !(file instanceof TFile)).length }; }
  async rebuild(): Promise<void> { const checks = this.checkins(); for (const member of this.members().filter(value => value.path.includes("/Members/"))) { const related = checks.filter(checkin => checkin.targets.includes(member.id) || checkin.ratings[member.id]); const latest = related[0]; const ratings = latest?.ratings[member.id] ?? {}; const ratingLines = Object.entries(ratings).map(([area, rating]) => `- ${area}: ${RATING_LABELS[ratingOf(rating)]}`).join("\n"); const body = [`## Member summary`, "", `- Role: ${member.role}`, `- Current needs: ${member.needs.join(", ") || "None recorded"}`, `- Current focuses: ${member.focuses.join(", ") || "None recorded"}`, "", "## Latest ratings", "", ratingLines || "Not recorded", "", "## Recent check-ins", "", ...(related.length ? related.slice(0, 8).map(checkin => `- ${checkin.date} — [[${checkin.path.replace(/\.md$/, "")}|${CHECKUP_LABELS[checkin.kind]}]]${checkin.legacy ? " · legacy shared" : ""}`) : ["No check-ins linked yet."])].join("\n"); await this.replace(member.path, MEMBER_START, MEMBER_END, body); } }
  private async replace(path: string, start: string, end: string, body: string): Promise<void> { const file = this.app.vault.getAbstractFileByPath(path); if (!(file instanceof TFile)) return; const current = await this.app.vault.read(file); const replacement = `${start}\n${body}\n${end}`; const escape = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const regex = new RegExp(`${escape(start)}[\\s\\S]*?${escape(end)}`); const next = regex.test(current) ? current.replace(regex, replacement) : `${current.trim()}\n\n${replacement}\n`; if (next !== current) await this.app.vault.process(file, () => next); }
}

class CheckinModal extends Modal {
  private kind: CheckupKind; private step = 0; private date = today(); private targets = new Set<string>(); private selectedAreas = new Set<string>(); private entryIndex = 0;
  private ratings: Record<string, Record<string, Rating>> = {}; private answers: Record<string, Record<string, string>> = {}; private focuses: Record<string, Record<string, string>> = {}; private nextSteps: Record<string, Record<string, string>> = {};
  constructor(app: App, private plugin: MarriageCompanionPlugin, initialKind?: CheckupKind, initialTarget?: string) { super(app); this.kind = initialKind ?? plugin.settings.defaultCheckupKind ?? "family"; if (initialTarget) this.targets.add(initialTarget); }
  onOpen(): void { this.modalEl.addClass("marriage-companion-modal"); this.render(); }
  private render(): void { this.contentEl.empty(); this.setTitle(`${CHECKUP_LABELS[this.kind]} · Step ${this.step + 1} of 4`); const host = this.contentEl.createDiv({ cls: "marriage-companion-wizard" }); if (this.step === 0) this.renderKind(host); else if (this.step === 1) this.renderTargets(host); else if (this.step === 2) this.renderAreas(host); else this.renderEntries(host); }
  private renderKind(host: HTMLElement): void { new Setting(host).setName("Check-in date").addText(text => { text.setValue(this.date); text.inputEl.type = "date"; text.onChange(value => this.date = value || today()); }); host.createEl("p", { text: "Choose the kind of conversation you are having. Keep it short and focused.", cls: "marriage-companion-muted" }); const cards = host.createDiv({ cls: "marriage-companion-choice-grid" }); (Object.keys(CHECKUP_LABELS) as CheckupKind[]).forEach(kind => { const button = cards.createEl("button", { text: CHECKUP_LABELS[kind], cls: kind === this.kind ? "is-selected" : "" }); button.onclick = () => { this.kind = kind; this.targets.clear(); this.selectedAreas.clear(); this.entryIndex = 0; this.render(); }; }); this.nav(host, false); }
  private renderTargets(host: HTMLElement): void { host.createEl("p", { text: this.kind === "family" ? "This checkup records the family as a group." : this.kind === "marriage" ? "Choose the marriage and both active spouses." : "Choose one or more active children to assess." }); const available = this.kind === "family" ? this.plugin.repository.targets().filter(target => target.kind === "family") : this.kind === "marriage" ? this.plugin.repository.targets().filter(target => target.id === "marriage" || target.kind === "member" && target.role?.toLowerCase() === "spouse") : this.plugin.repository.targets().filter(target => target.kind === "member" && target.role?.toLowerCase() === "child"); if (this.kind === "marriage" && this.plugin.settings.requireSpouses !== false && this.plugin.repository.spouses().length < 2) { host.createEl("p", { text: "Marriage checkups need two active spouse profiles.", cls: "marriage-companion-care" }); const add = host.createEl("button", { text: "Add spouse profile" }); add.onclick = () => new MemberModal(this.app, this.plugin, "spouse").open(); } const picker = host.createDiv({ cls: "marriage-companion-target-picker" }); available.forEach(target => { const label = picker.createEl("label", { cls: "marriage-companion-target-option" }); const check = label.createEl("input", { type: "checkbox" }); check.checked = this.targets.has(target.id); label.createSpan({ text: target.label }); check.onchange = () => check.checked ? this.targets.add(target.id) : this.targets.delete(target.id); }); this.nav(host, true); }
  private renderAreas(host: HTMLElement): void { const chosen = this.plugin.repository.targets().filter(target => this.targets.has(target.id)); const union = new Map<string, Area>(); chosen.forEach(target => this.plugin.repository.areasFor(this.kind, target).forEach(area => union.set(area.id, area))); host.createEl("p", { text: "Select only the categories that fit this conversation.", cls: "marriage-companion-muted" }); const picker = host.createDiv({ cls: "marriage-companion-area-picker" }); [...union.values()].sort((a, b) => (a.order ?? 0) - (b.order ?? 0)).forEach(area => { const label = picker.createEl("label", { cls: "marriage-companion-target-option" }); const check = label.createEl("input", { type: "checkbox" }); check.checked = this.selectedAreas.has(area.id); label.createSpan({ text: area.name }); check.onchange = () => check.checked ? this.selectedAreas.add(area.id) : this.selectedAreas.delete(area.id); }); this.nav(host, true); }
  private renderEntries(host: HTMLElement): void { const targets = this.plugin.repository.targets().filter(target => this.targets.has(target.id)); const pairs = targets.flatMap(target => [...this.selectedAreas].filter(areaId => this.plugin.repository.areasFor(this.kind, target).some(area => area.id === areaId)).map(areaId => ({ target, area: this.plugin.settings.areas.find(area => area.id === areaId)! }))); const pair = pairs[this.entryIndex]; if (!pair) { host.createEl("p", { text: "Choose at least one category.", cls: "marriage-companion-muted" }); return; } host.createEl("p", { text: `${pair.target.label} · ${pair.area.name}`, cls: "marriage-companion-eyebrow" }); host.createEl("small", { text: pair.area.promptByCheckup?.[this.kind] ?? pair.area.prompt, cls: "marriage-companion-muted" }); this.ratings[pair.target.id] ??= {}; this.answers[pair.target.id] ??= {}; this.focuses[pair.target.id] ??= {}; this.nextSteps[pair.target.id] ??= {}; new Setting(host).setName("Rating").addDropdown(dropdown => dropdown.addOptions(RATING_LABELS).setValue(this.ratings[pair.target.id][pair.area.id] ?? pair.area.defaultRating ?? "healthy").onChange(value => this.ratings[pair.target.id][pair.area.id] = value as Rating)); new Setting(host).setName("Short answer").addTextArea(text => text.setValue(this.answers[pair.target.id][pair.area.id] ?? "").onChange(value => this.answers[pair.target.id][pair.area.id] = value)); new Setting(host).setName("Current focus").addText(text => text.setValue(this.focuses[pair.target.id][pair.area.id] ?? "").onChange(value => this.focuses[pair.target.id][pair.area.id] = value)); new Setting(host).setName("Next step").addText(text => text.setValue(this.nextSteps[pair.target.id][pair.area.id] ?? "").onChange(value => this.nextSteps[pair.target.id][pair.area.id] = value)); host.createEl("p", { text: `Scripture prompt: ${pair.area.scriptures.join(" · ")}`, cls: "marriage-companion-scripture" }); const nav = host.createDiv({ cls: "marriage-companion-wizard-nav" }); if (this.entryIndex > 0) this.button(nav, "Back", () => { this.entryIndex--; this.render(); }); if (this.entryIndex < pairs.length - 1) this.button(nav, "Next", () => { this.entryIndex++; this.render(); }, true); else this.button(nav, "Save checkup", () => void this.save(), true); }
  private nav(host: HTMLElement, back: boolean): void { const nav = host.createDiv({ cls: "marriage-companion-wizard-nav" }); if (back) this.button(nav, "Back", () => { this.step--; this.render(); }); this.button(nav, this.step === 2 ? "Begin entries" : "Continue", () => { if (this.step === 1 && !this.validTargets()) return; if (this.step === 2 && !this.selectedAreas.size) { new Notice("Choose at least one category."); return; } this.step++; this.entryIndex = 0; this.render(); }, true); }
  private validTargets(): boolean { if (this.kind === "family" && !this.targets.has("family")) { new Notice("Select Whole family."); return false; } if (this.kind === "marriage" && this.plugin.settings.requireSpouses !== false && (this.targets.size < 3 || this.plugin.repository.spouses().length < 2)) { new Notice("Select Marriage and two spouse profiles."); return false; } if (this.kind === "kids" && !this.targets.size) { new Notice("Select at least one child."); return false; } return true; }
  private button(parent: HTMLElement, text: string, action: () => void, primary = false): void { const button = parent.createEl("button", { text }); if (primary) button.addClass("mod-cta"); button.onclick = action; }
  private async save(): Promise<void> { if (!this.validTargets()) return; await this.plugin.repository.createCheckin({ kind: this.kind, date: this.date, targets: [...this.targets], ratings: this.ratings, answers: this.answers, focuses: this.focuses, nextSteps: this.nextSteps }); await this.plugin.repository.rebuild(); this.close(); await this.plugin.refreshDashboard(); new Notice(`${CHECKUP_LABELS[this.kind]} saved.`); }
}

class MemberModal extends Modal { private name = ""; private role: string; private needs = ""; private focuses = ""; constructor(app: App, private plugin: MarriageCompanionPlugin, role = "child") { super(app); this.role = role; } onOpen(): void { this.modalEl.addClass("marriage-companion-modal"); this.setTitle("Add family member"); new Setting(this.contentEl).setName("Name").addText(text => text.onChange(value => this.name = value)); new Setting(this.contentEl).setName("Role").addDropdown(dropdown => dropdown.addOptions({ spouse: "Spouse", child: "Child", other: "Other household member" }).setValue(this.role).onChange(value => this.role = value)); new Setting(this.contentEl).setName("Current needs").setDesc("Comma-separated").addText(text => text.onChange(value => this.needs = value)); new Setting(this.contentEl).setName("Current focuses").setDesc("Comma-separated").addText(text => text.onChange(value => this.focuses = value)); const actions = this.contentEl.createDiv({ cls: "marriage-companion-wizard-nav" }); const save = actions.createEl("button", { text: "Add member", cls: "mod-cta" }); save.onclick = async () => { if (!this.name.trim()) { new Notice("A name is required."); return; } await this.plugin.repository.createMember(this.name.trim(), this.role, this.needs.split(",").map(value => value.trim()).filter(Boolean), this.focuses.split(",").map(value => value.trim()).filter(Boolean)); this.close(); await this.plugin.refreshDashboard(); }; } }

class AreasModal extends Modal { constructor(app: App, private plugin: MarriageCompanionPlugin) { super(app); } onOpen(): void { this.modalEl.addClass("marriage-companion-modal"); this.setTitle("Manage checkup areas"); const host = this.contentEl.createDiv({ cls: "marriage-companion-areas-editor" }); const areas = this.plugin.settings.areas.map(area => ({ ...area, scriptures: [...area.scriptures], enabledTargets: area.enabledTargets ? [...area.enabledTargets] : undefined, enabledCheckups: area.enabledCheckups ? [...area.enabledCheckups] : undefined })); for (const area of areas) { const fields = host.createDiv({ cls: "marriage-companion-area-editor" }); new Setting(fields).setName("Name").addText(text => text.setValue(area.name).onChange(value => area.name = value)); new Setting(fields).setName("Order").addText(text => text.setValue(String(area.order ?? 1)).onChange(value => area.order = Number(value) || 1)); new Setting(fields).setName("Default rating").addDropdown(dropdown => dropdown.addOptions(RATING_LABELS).setValue(area.defaultRating ?? "healthy").onChange(value => area.defaultRating = value as Rating)); new Setting(fields).setName("Checkups").setDesc("family, marriage, kids; blank = all").addText(text => text.setValue((area.enabledCheckups ?? []).join(", ")).onChange(value => { const selected = value.split(/[,;\n]/).map(item => item.trim().toLowerCase()).filter(item => ["family", "marriage", "kids"].includes(item)) as CheckupKind[]; area.enabledCheckups = selected.length ? selected : undefined; })); new Setting(fields).setName("Targets").setDesc("family, marriage, member; blank = all").addText(text => text.setValue((area.enabledTargets ?? []).join(", ")).onChange(value => { const selected = value.split(/[,;\n]/).map(item => item.trim().toLowerCase()).filter(item => ["family", "marriage", "member"].includes(item)) as TargetKind[]; area.enabledTargets = selected.length ? selected : undefined; })); new Setting(fields).setName("Scripture").addText(text => text.setValue(area.scriptures.join(", ")).onChange(value => area.scriptures = value.split(/[,;\n]/).map(item => item.trim()).filter(Boolean))); new Setting(fields).setName("Prompt").addTextArea(text => text.setValue(area.prompt).onChange(value => area.prompt = value)); } const actions = this.contentEl.createDiv({ cls: "marriage-companion-wizard-nav" }); const save = actions.createEl("button", { text: "Save areas", cls: "mod-cta" }); save.onclick = async () => { this.plugin.settings.areas = areas.sort((a, b) => (a.order ?? 0) - (b.order ?? 0)).map((area, index) => ({ ...area, order: index + 1, name: area.name.trim() || `Area ${index + 1}` })); await this.plugin.saveSettings(); this.close(); }; } }

class TargetView extends ItemView {
  constructor(leaf: WorkspaceLeaf, private plugin: MarriageCompanionPlugin, private targetId = "family") { super(leaf); }
  getViewType(): string { return VIEW; }
  getDisplayText(): string { return "Family Companion"; }
  getIcon(): string { return "heart-handshake"; }
  async onOpen(): Promise<void> { await this.render(); }
  async render(): Promise<void> {
    const root = this.containerEl.children[1] as HTMLElement; root.empty(); root.addClass("marriage-companion-dashboard");
    const checks = this.plugin.repository.checkins(); const targets = this.plugin.repository.targets(); const activeTarget = targets.find(target => target.id === this.targetId) ?? targets[0]; const latest = activeTarget ? this.plugin.repository.latestFor(activeTarget.id) : undefined;
    const hero = root.createDiv({ cls: "marriage-companion-hero" }); hero.createEl("div", { text: "RED-BEARD  ·  FAMILY COMPANION", cls: "marriage-companion-eyebrow" }); hero.createEl("h1", { text: activeTarget?.label ?? "Family Companion" }); hero.createEl("p", { text: this.plugin.repository.due() ? "Make space to pray, listen, and pursue one another with honest hope in Christ." : `Last checkup: ${latest?.date ?? "—"}` });
    const actions = hero.createDiv({ cls: "marriage-companion-actions" }); this.button(actions, "Family checkup", () => new CheckinModal(this.app, this.plugin, "family").open(), true); this.button(actions, "Marriage checkup", () => new CheckinModal(this.app, this.plugin, "marriage").open()); this.button(actions, "Kids checkup", () => new CheckinModal(this.app, this.plugin, "kids").open()); this.button(actions, "Add member", () => new MemberModal(this.app, this.plugin).open()); this.button(actions, "Manage areas", () => new AreasModal(this.app, this.plugin).open()); this.button(actions, "Refresh", () => void this.plugin.rebuild()); this.button(actions, "Settings", () => this.plugin.openSettings());
    const metrics = root.createDiv({ cls: "marriage-companion-metrics" }); this.metric(metrics, String(checks.length), "Checkups"); this.metric(metrics, String(Math.max(0, targets.length - 2)), "Members"); this.metric(metrics, String(this.countNeeds(latest, activeTarget?.id)), "Areas needing care"); this.metric(metrics, latest?.date ? shortDate(latest.date) : "—", "Last checkup");
    const picker = root.createDiv({ cls: "marriage-companion-target-tabs" }); targets.forEach(target => { const button = picker.createEl("button", { text: target.label, cls: target.id === activeTarget?.id ? "is-active" : "" }); button.onclick = () => { this.targetId = target.id; void this.render(); }; });
    this.renderSnapshot(root, activeTarget, latest); this.renderComparison(root, targets, checks, activeTarget); this.renderHistory(root, checks, activeTarget);
  }
  private renderSnapshot(root: HTMLElement, target: Target | undefined, latest: CheckIn | undefined): void { const section = root.createDiv({ cls: "marriage-companion-section" }); section.createEl("h2", { text: `${target?.label ?? "Family"} snapshot` }); section.createEl("p", { text: latest ? `${latest.legacy ? "Shared legacy checkup · " : CHECKUP_LABELS[latest.kind] + " · "}${shortDate(latest.date)}` : "Not recorded yet.", cls: "marriage-companion-muted" }); const grid = section.createDiv({ cls: "marriage-companion-health-grid" }); for (const area of this.plugin.settings.areas.filter(item => !item.enabledCheckups?.length || item.enabledCheckups.includes(latest?.kind ?? "family"))) { const rating = latest?.ratings[target?.id ?? ""]?.[area.id]; const card = grid.createDiv({ cls: `marriage-companion-health-card is-${rating ?? "empty"}` }); card.createEl("strong", { text: area.name }); card.createEl("span", { text: rating ? `${RATING_SYMBOLS[ratingOf(rating)]} ${RATING_LABELS[ratingOf(rating)]}` : "Not recorded" }); if (rating && RATING_ORDER.indexOf(ratingOf(rating)) >= 2) card.createEl("small", { text: area.promptByCheckup?.[latest?.kind ?? "family"] ?? area.prompt }); } }
  private renderComparison(root: HTMLElement, targets: Target[], checks: CheckIn[], activeTarget: Target | undefined): void { const section = root.createDiv({ cls: "marriage-companion-section" }); section.createEl("h2", { text: "Target comparison" }); section.createEl("p", { text: "Ratings stay separate so family, marriage, spouses, and children can differ honestly.", cls: "marriage-companion-muted" }); const compareTargets = activeTarget?.kind === "member" ? targets.filter(target => target.id === "family" || target.id === "marriage" || target.id === activeTarget.id) : targets.filter(target => target.kind === activeTarget?.kind || target.id === "family" || target.id === "marriage").slice(0, 8); const table = section.createDiv({ cls: "marriage-companion-comparison-grid" }); table.createEl("strong", { text: "Category" }); compareTargets.forEach(target => table.createEl("strong", { text: target.label })); for (const area of this.plugin.settings.areas) { table.createEl("span", { text: area.name }); compareTargets.forEach(target => { const record = checks.find(check => check.targets.includes(target.id) || check.ratings[target.id]); const rating = record?.ratings[target.id]?.[area.id]; table.createEl("span", { text: rating ? RATING_LABELS[ratingOf(rating)] : "Not recorded", cls: rating ? `is-${ratingOf(rating)}` : "marriage-companion-muted" }); }); } }
  private renderHistory(root: HTMLElement, checks: CheckIn[], target: Target | undefined): void { const section = root.createDiv({ cls: "marriage-companion-section" }); section.createEl("h2", { text: "Recent checkups" }); checks.filter(item => item.targets.includes(target?.id ?? "") || item.ratings[target?.id ?? ""]).slice(0, this.plugin.settings.trendHistory ?? 8).forEach(check => { const row = section.createDiv({ cls: "marriage-companion-recent-row" }); row.createEl("strong", { text: shortDate(check.date) }); row.createSpan({ text: check.legacy ? "Shared legacy checkup" : CHECKUP_LABELS[check.kind], cls: "marriage-companion-muted" }); this.button(row, "Open", () => void this.plugin.openFile(check.path)); }); if (!checks.length) section.createEl("p", { text: "No checkups yet.", cls: "marriage-companion-empty" }); }
  private countNeeds(check: CheckIn | undefined, target: string | undefined): number { return check && target ? this.plugin.settings.areas.filter(area => RATING_ORDER.indexOf(ratingOf(check.ratings[target]?.[area.id])) >= 2).length : 0; }
  private button(parent: HTMLElement, text: string, action: () => void, primary = false): void { const button = parent.createEl("button", { text }); if (primary) button.addClass("mod-cta"); button.onclick = action; }
  private metric(parent: HTMLElement, value: string, label: string): void { const card = parent.createDiv({ cls: "marriage-companion-metric" }); card.createEl("strong", { text: value }); card.createEl("span", { text: label }); }
}

class MarriageSettings extends PluginSettingTab {
  constructor(app: App, private plugin: MarriageCompanionPlugin) { super(app, plugin); }
  display(): void {
    const { containerEl } = this; containerEl.empty(); containerEl.createEl("h2", { text: "Family Companion" });
    new Setting(containerEl).setName("Family root folder").addText(text => text.setValue(this.plugin.settings.rootFolder).onChange(async value => { this.plugin.settings.rootFolder = value.trim() || DEFAULT.rootFolder; await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("Default checkup type").addDropdown(dropdown => dropdown.addOptions(CHECKUP_LABELS).setValue(this.plugin.settings.defaultCheckupKind ?? "family").onChange(async value => { this.plugin.settings.defaultCheckupKind = value as CheckupKind; await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("Require two spouse profiles").addToggle(toggle => toggle.setValue(this.plugin.settings.requireSpouses ?? true).onChange(async value => { this.plugin.settings.requireSpouses = value; await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("Trend history length").addSlider(slider => slider.setLimits(3, 20, 1).setValue(this.plugin.settings.trendHistory ?? 8).setDynamicTooltip().onChange(async value => { this.plugin.settings.trendHistory = value; await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("Check-in cadence").addDropdown(dropdown => dropdown.addOptions({ weekly: "Weekly", biweekly: "Biweekly", monthly: "Monthly" }).setValue(this.plugin.settings.cadence).onChange(async value => { this.plugin.settings.cadence = value as Cadence; await this.plugin.saveSettings(); }));
    containerEl.createEl("p", { text: "Records are ordinary Markdown notes. This plugin does not encrypt records or provide emergency, medical, or counseling services." });
    const actions = containerEl.createDiv({ cls: "marriage-companion-wizard-nav" }); const preview = actions.createEl("button", { text: "Preview v3 migration" }); preview.onclick = () => void this.plugin.previewMigration(); const migrate = actions.createEl("button", { text: "Run v3 migration" }); migrate.onclick = () => void this.plugin.runMigration(); const verify = actions.createEl("button", { text: "Verify migration" }); verify.onclick = () => this.plugin.verifyMigration();
  }
}

export default class MarriageCompanionPlugin extends Plugin {
  settings: Settings = DEFAULT; repository!: FamilyRepository;
  async onload(): Promise<void> {
    this.settings = { ...DEFAULT, ...(await this.loadData() as Partial<Settings> | null) }; this.settings.areas = (this.settings.areas?.length ? this.settings.areas : DEFAULT_AREAS).map((area, index) => { const base = DEFAULT_AREAS.find(item => item.id === area.id); return { ...base, ...area, order: area.order ?? index + 1, defaultRating: area.defaultRating ?? base?.defaultRating ?? "healthy", enabledTargets: area.enabledTargets ?? base?.enabledTargets, enabledCheckups: area.enabledCheckups ?? base?.enabledCheckups, scriptures: area.scriptures?.length ? area.scriptures : base?.scriptures ?? [], prompt: area.prompt || base?.prompt || "" }; }); this.settings.defaultCheckupKind ??= "family"; this.settings.requireSpouses ??= true; this.settings.trendHistory ??= 8;
    this.repository = new FamilyRepository(this.app, this.settings); try { await this.repository.initialize(); } catch (error) { console.error("Family Companion could not initialize its folders.", error); new Notice(`Family Companion could not initialize its folders: ${error instanceof Error ? error.message : String(error)}`); }
    this.registerView(VIEW, leaf => new TargetView(leaf, this)); this.addSettingTab(new MarriageSettings(this.app, this)); this.addRibbonIcon("heart-handshake", "Open Family Companion", () => void this.openDashboard());
    this.addCommand({ id: "open-dashboard", name: "Open family dashboard", callback: () => void this.openDashboard() }); this.addCommand({ id: "new-checkin", name: "Start family checkup", callback: () => new CheckinModal(this.app, this, "family").open() }); this.addCommand({ id: "new-marriage-checkin", name: "Start marriage checkup", callback: () => new CheckinModal(this.app, this, "marriage").open() }); this.addCommand({ id: "new-family-checkin", name: "Start family checkup", callback: () => new CheckinModal(this.app, this, "family").open() }); this.addCommand({ id: "new-kids-checkin", name: "Start kids checkup", callback: () => new CheckinModal(this.app, this, "kids").open() }); this.addCommand({ id: "new-member-checkin", name: "Start member checkup", callback: () => new CheckinModal(this.app, this, "kids", this.repository.children()[0]?.id).open() }); this.addCommand({ id: "add-member", name: "Add family member", callback: () => new MemberModal(this.app, this).open() }); this.addCommand({ id: "add-child", name: "Add child profile (compatibility)", callback: () => new MemberModal(this.app, this, "child").open() }); this.addCommand({ id: "manage-areas", name: "Manage family checkup areas", callback: () => new AreasModal(this.app, this).open() });
    this.addCommand({ id: "open-family-view", name: "Open family view", callback: () => void this.openTarget("family") }); this.addCommand({ id: "open-marriage-view", name: "Open marriage view", callback: () => void this.openTarget("marriage") }); this.addCommand({ id: "open-kids-view", name: "Open kids view", callback: () => void this.openTarget(this.repository.children()[0]?.id ?? "family") }); this.addCommand({ id: "open-member-view", name: "Open member view", callback: () => void this.openTarget(this.repository.members()[0]?.id ?? "family") }); this.addCommand({ id: "open-index", name: "Open family index (compatibility)", callback: () => void this.openDashboard() }); this.addCommand({ id: "rebuild-summaries", name: "Refresh family summaries", callback: () => void this.rebuild() }); this.addCommand({ id: "refresh-summaries", name: "Refresh summaries", callback: () => void this.rebuild() }); this.addCommand({ id: "preview-migration", name: "Preview Family Companion migration", callback: () => void this.previewMigration() }); this.addCommand({ id: "run-migration", name: "Run Family Companion migration", callback: () => void this.runMigration() }); this.addCommand({ id: "verify-migration", name: "Verify Family Companion migration", callback: () => this.verifyMigration() }); this.addCommand({ id: "restore-migration", name: "Restore Family Companion migration backup", callback: () => new Notice("Restore is manual: review the verified backup folder before restoring records.") });
  }
  async saveSettings(): Promise<void> { await this.saveData(this.settings); this.repository.update(this.settings); await this.refreshDashboard(); }
  async openDashboard(): Promise<void> { await this.repository.initialize(); let leaf = this.app.workspace.getLeavesOfType(VIEW)[0]; if (!leaf) { leaf = this.app.workspace.getLeaf("tab"); await leaf.setViewState({ type: VIEW, active: true }); } await this.app.workspace.revealLeaf(leaf); }
  async openTarget(target: string): Promise<void> { await this.openDashboard(); const view = this.app.workspace.getLeavesOfType(VIEW)[0]?.view; if (view instanceof TargetView) { view["targetId"] = target; await view.render(); } }
  openSettings(): void { const settingsApp = this.app as App & { setting: { open(): void; openTabById(id: string): void } }; settingsApp.setting.open(); settingsApp.setting.openTabById(this.manifest.id); }
  async rebuild(): Promise<void> { await this.repository.rebuild(); new Notice("Family summaries refreshed."); await this.refreshDashboard(); }
  async previewMigration(): Promise<void> { const checks = this.repository.checkins(); const legacy = checks.filter(check => check.legacy || !check.path.includes("v3")) .length; new Notice(`Migration preview: ${checks.length} check-in(s), ${legacy} shared/legacy record(s). No files changed.`); }
  async runMigration(): Promise<void> { const result = await this.repository.migrateV3(); this.settings.migrationVersion = 3; await this.saveData(this.settings); new Notice(`Migration complete: ${result.changed} record(s). Backup and journal created.`); await this.refreshDashboard(); }
  verifyMigration(): void { const result = this.repository.verifyMigration(); new Notice(`Family Companion verification: ${result.legacy} legacy, ${result.v3} v3 check-ins, ${result.members} members, ${result.backups} backup folder(s).`); }
  async openFile(path: string): Promise<void> { const file = this.app.vault.getAbstractFileByPath(path); if (file instanceof TFile) await this.app.workspace.getLeaf("tab").openFile(file); }
  async refreshDashboard(): Promise<void> { const view = this.app.workspace.getLeavesOfType(VIEW)[0]?.view; if (view instanceof TargetView) await view.render(); }
}

const rbDisposals = new WeakMap<object, () => void>(); const rbOnload = MarriageCompanionPlugin.prototype.onload;
MarriageCompanionPlugin.prototype.onload = async function(this: MarriageCompanionPlugin) { await rbOnload.call(this); const disposals = [registerDashboardModule(this.app, { id: "marriage-companion", name: "Family Companion", command: "marriage-companion:open-dashboard", icon: "heart-handshake", description: "Family, marriage, and child checkups.", order: 20 }), registerDashboardWidget(this.app, { id: "marriage-companion/overview", name: "Family Companion", description: "Transparent family health snapshots.", icon: "heart-handshake", defaultLayout: { w: 4, mobileW: 12, h: 2, order: 40 }, mobile: "responsive", render: (_ctx, container) => { container.createEl("p", { text: "Family, marriage, and child checkups." }); const button = container.createEl("button", { text: "Open Family Companion" }); button.onclick = () => void this.openDashboard(); } })]; rbDisposals.set(this, () => disposals.forEach(dispose => dispose())); };
const rbOnunload = MarriageCompanionPlugin.prototype.onunload; MarriageCompanionPlugin.prototype.onunload = function(this: MarriageCompanionPlugin) { rbDisposals.get(this)?.(); return rbOnunload ? rbOnunload.call(this) : undefined; };
